apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc 
  labels:
    env: demo
spec:
  type: NodePort
  ports:
    - nodePort: 30001 # the port on which the service will be exposed on the nodes
      port: 80        # the port on which the service is listening inside all nodes
      targetPort: 80  # the port on which the container is listening inside the pod 
  selector: # specifies which pods the Service should route traffic to
    env: demo